package kg.nurtelecom.o.talkingavatar.ui.avatar

object FacialBlendShape {
    const val EYE_BLINK_LEFT = "eyeBlinkLeft"
    const val EYE_BLINK_RIGHT = "eyeBlinkRight"
    const val EYES_CLOSED = "eyesClosed"
    const val EYE_WIDE_LEFT = "eyeWideLeft"
    const val EYE_WIDE_RIGHT = "eyeWideRight"
    const val EYE_LOOK_UP_LEFT = "eyeLookUpLeft"
    const val EYE_LOOK_UP_RIGHT = "eyeLookUpRight"
    const val EYE_LOOK_DOWN_LEFT = "eyeLookDownLeft"
    const val EYE_LOOK_DOWN_RIGHT = "eyeLookDownRight"
    const val EYE_LOOK_IN_LEFT = "eyeLookInLeft"
    const val EYE_LOOK_IN_RIGHT = "eyeLookInRight"
    const val EYE_LOOK_OUT_LEFT = "eyeLookOutLeft"
    const val EYE_LOOK_OUT_RIGHT = "eyeLookOutRight"
    const val BROW_INNER_UP = "browInnerUp"
    const val BROW_DOWN_LEFT = "browDownLeft"
    const val BROW_DOWN_RIGHT = "browDownRight"
    const val BROW_OUTER_UP_LEFT = "browOuterUpLeft"
    const val BROW_OUTER_UP_RIGHT = "browOuterUpRight"
    const val MOUTH_SMILE = "mouthSmile"
    const val MOUTH_SMILE_LEFT = "mouthSmileLeft"
    const val MOUTH_SMILE_RIGHT = "mouthSmileRight"
    const val MOUTH_FROWN_LEFT = "mouthFrownLeft"
    const val MOUTH_FROWN_RIGHT = "mouthFrownRight"
    const val JAW_OPEN = "jawOpen"
    const val JAW_FORWARD = "jawForward"
    const val MOUTH_OPEN = "mouthOpen"
    const val MOUTH_SHRUG_LOWER = "mouthShrugLower"
    const val MOUTH_LOWER_DOWN_LEFT = "mouthLowerDownLeft"
    const val MOUTH_LOWER_DOWN_RIGHT = "mouthLowerDownRight"
    const val CHEEK_PUFF = "cheekPuff"
}
